#!/bin/sh -e

##########################################################################
#   Script description:
#       Auto-format columns in scientific notation with a given cutoff
#       
#   History:
#   Date        Name        Modification
#   2020-09-23  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 FS cutoff sig-figs col1 [col2 ...]

Example:

    Space or tab separator
    Scientific notation for values < 10^-2
    10 significant figures
    Columns 1, 5, and 6

$0 '[ \\\t]' 0.01 10 1 5 6

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 4 ]; then
    usage
fi
fs="$1"
shift
cutoff=$1
shift
sig_figs=$1
shift
col_str="$@"

awk -F $fs -f format-cols.awk \
    -v cutoff=$cutoff \
    -v sig_figs=$sig_figs \
    -v col_str="$col_str"
